### ISSUE TITLE
메인화면 다이얼 dismiss관련 오류(viewWillDisappear 관련)

### ISSUE THREAD

**Issue by joongkyu-park** [depromeet/street-drop-iOS#157]
### 요청 사항

커뮤니티 화면이나 검색 화면으로 넘어갈 때 다이얼을 dismiss해야함.
따라서 이 구현을 viewWillDisappear 처리하고 있는데, 이와 관련해서 오류가 발생하는 것 같아 수정 필요

**Comment by joseph704** [comment]
해당 이슈 현재 (1.0.3.4) 버전에서 재현되지 않아(아마 예전에 수정하신듯!) 클로즈
