### ISSUE TITLE
[메인] 컴포넌트 디테일(반경 오버레이 이미지, 코멘트 말풍선 쉐도우 효과)

### ISSUE THREAD

**Issue by joongkyu-park** [depromeet/street-drop-iOS#201]
### 요청 사항

![image](https://github.com/depromeet/street-drop-iOS/assets/60916423/98902228-57c3-4ceb-8629-28b58bcb11c4)

**Comment by joseph704** [comment]
[b26d829](https://github.com/depromeet/street-drop-iOS/commit/b26d829f4c45698cb806753d4909bae3ff795c9b) 에서 해당 이슈에 대한 사항들 적용
