### ISSUE TITLE
대한민국 전체 poi 안찍히는 현상

### ISSUE THREAD

**Issue by joseph704** [depromeet/street-drop-iOS#204]
### 버그 설명

대한민국 전체 poi 안찍히는 현상, 앱 실행 시, 현재 위치 반경 200km만 poi 찍힘

### 버그 발생 절차

수도권에서 앱 실행시 먼 지역(경남, 제주)은 안보임

### 기대 동작

대한민국 전체 poi 노출됨

### 환경 정보

Device: iPhone 12 mini
iOS: iOS 16.2
Xcode: 14.2

**Comment by seonghun-dev** [comment]
현재 가지고 있는 모든 poi 찍는 api 하나 드릴까요?

**Comment by joseph704** [comment]
> 현재 가지고 있는 모든 poi 찍는 api 하나 만들어
> 드릴까요?

@seonghun-dev 기존 poi처럼 앨범 이미지도 포함되어 있는 api 인가요??

**Comment by seonghun-dev** [comment]
네네 아무요청없이 현재 가지고 있는 모든 poi 찍는 api 추가로 만들어서 전달드릴 수는 있을 것 같습니다
