### ISSUE TITLE
위치 정보를 한글 주소로 정확하게 수정하기

### ISSUE THREAD

**Issue by joongkyu-park** [depromeet/street-drop-iOS#76]
### 요청 사항

현재 좌표값을 가지고 geocoder.reverseGeocodeLocation를 이용해서 한글 주소를 얻어올 수 있으나,
서버에서 요구하는 포맷(ex. 종로구 사직동)과는 달라서 맞추기 위한 수정 필요

**Comment by joseph704** [comment]
@joongkyu-park 
#107 
서버에서 한글주소 내려주기로 하여, 이 이슈는 클로즈 하겠습니다!
