### ISSUE TITLE
상황에 따른 상세정보 API 갱신

### ISSUE THREAD

**Issue by joongkyu-park** [depromeet/street-drop-iOS#78]
### 요청 사항

~일정 주기로 위치 정보 업데이트되도록 구현~ -> 상황에 따른 상세정보 API 갱신

1. POI 랑 주변 마커 보는거
- 처음 앱 킬 때, Poi요청 API로 지도에 뿌리기
- 지도가 움직이고, 사용자가 움직이는 상황에선 지도상의 앨범들을 들을 수 있는상태인지, 아닌지 중요하지않으므로 추가 API 쏘지않음

2. 확인 플로우
- 핀터치할 때 -> 상세정보 API찔러서 들을 수 있는 리스트 가져오기
- 서버에서 가져온 배열 터치한 pin의 ItemID가 있을 때 리스트 제공

3. 드랍플로우
- 정책상 드랍버튼 터치할때의 위치에 드랍하기로 했으므로 드랍버튼 터치할 때 위치정보를 다시 가져오기

**Comment by joseph704** [comment]
바뀌는 부분이 많아, 바뀌는 기능에 대해서 이슈를 재생성함에, 해당 이슈를 닫습니다!
